### ISSUE TITLE
Nonstandard baud rates

### ISSUE THREAD

**Issue by samkristoff** [albenik/go-serial#2]
Any ideas on how to support non-standard baud rates? I'm specifically trying to use 1,250,000

Thanks!

**Comment by renathoaz** [comment]
@samkristoff 
I did a little trick to make it possible on linux: https://github.com/renathoaz/go-serial

try it.

**Comment by albenik** [comment]
@renathoaz Please look at https://github.com/albenik/go-serial/commit/fba195e3aed21b86c2fab0fce57b9eb55687208c

I took you first implementation and implemented it ONLY for linux build. Because no `unix.TCGETS`, `unix.TCGETS2` on darwin or freebsd and I have no time to research implementation for non-linux os.

**Comment by renathoaz** [comment]
@albenik I missed this detail, I was with a little urgency to have custom baudrates. Well I tested your implementation with my device that runs on 5787 baudrate. Everything worked fine. I will use your lib, since  I have no free time to give maintenance to mine fork.  I will wait for you merge. Thank you for your lib and time.
